#! /bin/sh

killall -q sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
#sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V

bspc config border_width        01
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#rule

#bspc rule -a firefox desktop='^2'
#bspc rule -a google-chrome desktop='^2' #follow=on
#bspc rule -a Chromium desktop='^2'  #follow=on
#bspc rule -a Subl desktop='^4'
#bspc rule -a code desktop='^4'
#bspc rule -a vlc desktop='^5'  follow=on
#bspc rule -a Spotify desktop='^5' follow=on

# Send to www desktop
bspc rule --add Firefox                     desktop='^2' follow=on
bspc rule firefox                        	desktop=2
bspc rule --add google-chrome-stable        desktop='^2' follow=on

# Send to dev desktop
bspc rule --add Atom                        desktop='^3' follow=on
bspc rule --add Subl                        desktop='^3' follow=on
#bspc rule --add Mysql-workbench-bin         desktop='dev' follow=on

# Send to play desktop
bspc rule --add Vlc                         desktop='^5' follow=on
#bspc rule --add Desura                      desktop='play' --one-shot follow=on


## Autostart

nm-applet &
$HOME/.config/polybar/bspwm.sh
feh --bg-fill ~/Imagens/wallpaper/nordic_01.jpg
betterlockscreen -u ~/Imagens/wallpaper/nordic_01.jpg
picom &
sh /home/essantos/.script/backup_dotfiles.sh &