#! /bin/sh

killall -q sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
#sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V

bspc config border_width        01
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on

bspc rule -a firefox desktop='^2'
bspc rule -a google-chrome desktop='^2' #follow=on
bspc rule -a Chromium desktop='^2'  #follow=on

bspc rule -a Subl desktop='^3'
bspc rule -a code desktop='^3'

bspc rule -a vlc desktop='^5'  follow=on
bspc rule -a Spotify desktop='^5' follow=on

## Autostart

nm-applet &
#$HOME/.config/polybar/launch.sh
$HOME/.config/polybar/bspwm.sh
feh --bg-fill ~/Imagens/wallpaper/nordic_01.jpg
#/usr/share/backgrounds/bspwm/wall.png
picom &
sh /home/essantos/.script/backup_dotfiles.sh &