#! /bin/sh

killall -q sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
#sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V
#bspc monitor -d 1 2 3 4 5

bspc config border_width        01
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#rule
#bspc rule -a subl desktop=’^2’ state=floating follow=on
bspc rule -a subl desktop=I focus=on
#bspc rule -a Gimp desktop=’^8’ state=floating follow=on
bspc rule -a "google-chrome-stable" desktop=’^2’
#bspc rule -a mplayer2 state=floating bspc rule -a
#Kupfer.py focus=on bspc rule -a Screenkey manage=off

#Fullscreen applications
#bspc rule -a inkscape state=fullscreen
bspc rule -a spotify state=fullscreen
bspc rule -a vlc state=fullscreen


## Autostart
xsetroot -cursor_name "Simp1e-Tokyo-Night" &
nm-applet &
$HOME/.config/polybar/bspwm.sh &
feh --bg-fill ~/Imagens/wallpaper/nordic_01.jpg &
#betterlockscreen -u ~/Imagens/wallpaper/nordic_01.jpg &
picom &
sh /home/essantos/.script/backup_dotfiles.sh &
